insert into product(name, category, price, manufacturer, unitInStock, description) values ("운동화", "shoes", 10, "나이키", 100, "초경량")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("노트북", "computer", 150, "삼성전자", 15, "최신형")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("TV", "appliances", 200, "LG전자", 30, "OLED")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("냉장고", "appliances", 150, "LG전자", 20, "4도어")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("구두", "shoes", 70, "구찌", 10, "비쌈")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("슬리퍼", "shoes", 2, "아디다스", 300, "쿠션 슬리퍼")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("휴대폰", "computer", 150, "APPLE", 20, "iPhone 11")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("세탁기", "appliances", 120, "LG전자", 50, "드럼세탁기")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("에어컨", "appliances", 60, "삼성전자", 30, "벽걸이 에어컨")
insert into product(name, category, price, manufacturer, unitInStock, description) values ("데스크탑", "computer", 110, "삼성전자", 5, "사무용")